# -*- coding: utf-8 -*-
"""week1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11IJEZFmA_GZCGDduUvTVHU92by4uE-hI
"""

#list methods
x=[1,2,3,4,5,6,"Excellent"]
print(x)
print(x[1:4])
print(x[:6])
x.insert(7,"work")
print(x)
x.remove(6)
print(x)
del(x[1])
print(x)
x.append("out there")
print(x)
print(len(x))
x.pop()
print(x)
y=["in","python"]
x.reverse()
print(x)
x.extend(y)
print(x)
x.clear()
print(x)

#dictionary methods
d={1:'A',2:'B',3:'C',4:'D',5:'E',6:'F'}
print(d)
print(type(d))
print(d.keys())
print(d.values())
print(d.pop(4))
x=d[1]
print(x)
y=d.get(5)
print(y)
d[6]='G'
print(d)
print(len(d))
d.clear()
print(d)

#tuple methods
x=(1,2,3,4,5,6)
print(x)
print(type(x))
print(x[2])
print(x[-5])
print(x[0:3])
t=list(x)
t.append(7)
x=tuple(t)
print(x)
y=len(x)
print(y)
print(any(x))
if 7 in x:
  print("is present in tuple")
else:
  print("not presennt")
for name in ('bunnu','sunny'):
    print("hello",name)

#set operatons
s={3,5,6,8}
print(s)
print(type(s))
s.add("numbers")
print(s) 
s.remove(5)
print(s) 
print(len(s))
s.discard(s)
print(s)
s.pop()
print(s)
s.clear()
print(s)

